name: OnPushIntoAllBranches

on:
  push:
    branches: ['*', '**']
  
jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: code analise
      run: ./vendor/bin/phpstan analyse --memory-limit=2G 
    
